apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
        - name: messaging-container
          image: messaging_web:latest  # Use your image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: messaging_app.settings
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP


metadata:
  name: django-blue
spec:
  template:
    spec:
      containers:
      - name: django-container
        image: your-dockerhub-username/django-app:v1
 
metadata:
  name: django-green
spec:
  template:
    spec:
      containers:
      - name: django-container
        image: your-dockerhub-username/django-app:v2

