#!/bin/bash
set -e

echo "Deploying Blue version..."
kubectl apply -f blue_deployment.yaml
kubectl apply -f kubeservice.yaml

echo "Deploying Green version..."
kubectl apply -f green_deployment.yaml

echo "Checking Blue pods..."
kubectl get pods -l app=django-blue

echo "Checking Green pods..."
kubectl get pods -l app=django-green

echo "Checking logs for Green version..."
kubectl logs -l app=django-green --tail=20

